#pragma once

// Generated by tools/generate_map.py. Do not edit manually.
namespace echoear_flight_radar_map {
static constexpr float CENTER_LATITUDE = 51.4700000f;
static constexpr float CENTER_LONGITUDE = -0.4543000f;
}  // namespace echoear_flight_radar_map
